### ISSUE TITLE
GridAgnet space_size 오류 

### ISSUE THREAD

**Issue by mjkim001130** [reinforcement-learning-kr/Unity_ML_Agents_2.0#73]
안녕하세요 책에서 GrideAgent.cs와 GirdArea.cs 모두 같게 수정하고, github에서 코드 복사해봤는데도
space_size가 6이 아닌 0으로 뜹니다 그대로 진행해도 상관없나요?
<img width="225" alt="image" src="https://github.com/reinforcement-learning-kr/Unity_ML_Agents_2.0/assets/79756320/3e80d788-1032-4f23-b61f-a55f750f92e5">

**Comment by Kyushik** [comment]
안녕하세요! 
BehaviorParameters의 Space Size는 직접 설정해주셔야하는 파라미터입니다. 
현재 벡터 관측의 수가 6이면 Space Size에 직접 6으로 설정하고 진행해주시면 됩니다!

**Comment by mjkim001130** [comment]
주말에 답변 감사합니다 :)
